name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"  # @daily
  workflow_dispatch:

jobs:
  windows_cpu_tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        torch: ["1.13.1", "2.2.2"]
        include:
          - torch: "1.13.1"
            torchvision: "0.14.1"
          - torch: "2.2.2"
            torchvision: "0.17.2"
    env:
      PYTORCH_INDEX: "https://download.pytorch.org/whl/cu118"
      DETECTRON2_DATASETS: ~/.torch/datasets
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        uses: ./.github/actions/install_windows_dep
        with:
          torch-version: ${{matrix.torch}}
          torchvision-version: ${{matrix.torchvision}}
          pytorch-index: $PYTORCH_INDEX

      - name: Install Detectron2
        uses: ./.github/actions/install_detectron2_win

      - name: Run Unit Tests
        uses: ./.github/actions/run_unittests_win

      - name: Build Wheel Package
        run: |
          python setup.py bdist_wheel

      - name: Upload Wheel to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-wheel
          path: dist/*.whl
